config/routes.rb
Rails.application.routes.draw do
  get 'login', :to => 'session#login', :as => :new_session
  post 'authorize', :to => 'session#authorize', :as => :authorize
  get 'callback', :to => 'session#callback', :as => :oauth_callback


  delete 'session/logout', :as => :destroy_session

  resources :folders

  resources :files, controller: 'documents', as: 'documents' do
    get 'upgrade', on: :member
  end

  root to: 'session#login'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/folder.rb
class Folder
  include ActiveModel::Model
  attr_accessor :id, :name, :id_parent_folder, :full_path, :created_at, :created_by, :updated_at, :updated_by, :contents
  attr_reader :type

  def initialize(options)
    super(options)
    @type = 1
  end

  def root?
    id.nil?
  end


end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :authorize
  before_action :set_folder_consumer
  before_action :set_document_consumer, only: [:show, :index]
  after_action :update_current_session


  # GET /folders
  # GET /folders.json
  def index
    # base_url, token, app_id, app_secret
    temp = @folder_client.index({id_parent_folder: -1})
    @contents = temp[:data]
    temp2 = @document_client.index(id_parent_folder: -1)
    @contents = @contents + temp2[:data]
    @current_folder = Folder.new({name: 'Root'})
    @success = temp[:status] and temp2[:status]

  end

  # GET /folders/1
  # GET /folders/1.json
  def show
    temp = @folder_client.index(id_parent_folder: get_id)
    @contents = temp[:data]
    temp2 = @folder_client.find(get_id)
    @folder = temp2[:data]
    temp3 = @document_client.index(id_parent_folder: get_id)
    @contents = @contents + temp3[:data]
    @success = temp[:status] and temp2[:status] and temp3[:status]
  end

  # GET /folders/new
  def new
    @folder = Folder.new(:id_parent_folder => (get_id_parent == '-1' ? nil : get_id_parent ))
    @fixed = (not get_id_parent.nil?)
    if @fixed
      if get_id_parent == '-1'
        temp = {status: true, response: 'Not Required'}
      else
        temp = @folder_client.find(id: get_id_parent)
        if temp[:status]
          @collection = [temp[:data]]
        end
      end
    else
      temp = @folder_client.index
      if temp[:status]
        @collection = temp[:data]
      end
    end
    @success = temp[:status]
  end

  # GET /folders/1/edit
  def edit
    temp = @folder_client.find(get_id)
    @folder = temp[:data]
    @fixed = false

    temp2 = @folder_client.index
    if temp2[:status]
      @collection = temp2[:data]
    end

    @success = temp[:status] and temp2[:status]
  end

  # POST /folders
  # POST /folders.json
  def create
    temp = @folder_client.create(params_create_folder)
    if temp[:status]
      flash_message(:notice,"#{t('folder.folder')} #{t('succesfully_created')}")
      folder_path(temp[:data].id)
    else
      flash_message(:error, 'Problema creando Carpeta')
      redirect_to root_path
    end
    @success = temp[:status]
  end

  # PATCH/PUT /folders/1
  # PATCH/PUT /folders/1.json
  def update
    temp = @folder_client.update(get_id, params_create_folder)
    if temp[:status]
      flash_message(:notice,"#{t('folder.folder')} #{t('succesfully_updated')}")
      redirect_to folder_path(temp[:data].id)
    else
      flash_message(:error, 'Problema actualizando Carpeta')
      redirect_to root_path
    end
    @success = temp[:status]
  end

  # DELETE /folders/1
  # DELETE /folders/1.json
  def destroy
    temp = @folder_client.destroy(get_id, force)
    if temp[:status]
      flash_message(:notice,"#{t('folder.folder')} #{t('succesfully_destroyed')}")
      redirect_to folders_path
    else
      if temp[:code] == 403
        @id = get_id
        @message = temp[:response]['message']
      else
        flash_message(:error, temp[:response]['message'])
        redirect_to root_path
      end

    end
    @success = temp[:status]
  end

  private

  def set_folder_consumer
    @folder_client = FolderConsumer.new(@current_session[:url], @current_session[:access_token], @current_session[:app_id], @current_session[:app_secret])
    @current_session[:access_token] = @folder_client.token.to_hash
  end

  def set_document_consumer
    @document_client = DocumentConsumer.new(@current_session[:url], @current_session[:access_token], @current_session[:app_id], @current_session[:app_secret])
    @current_session[:access_token] = @document_client.token.to_hash
  end

  def update_current_session
    session[:current_session] = @current_session.to_json(:include => :access_token)
  end

  def get_id
    if params.has_key? :id
      params[:id]
    else
      flash_message(:error, t('error.provide_id'))
      redirect_to root_path
    end
  end

  def get_id_parent
    if params.has_key? :id_parent_folder and not params[:id_parent_folder].blank?
      params[:id_parent_folder]
    else
      nil
    end
  end

  def force
    ((params.has_key? :force and params[:force] == '1' )? 1 : 0)
  end

  def params_create_folder
    temp = params.require(:folder).permit(:name, :id_parent_folder)
    unless temp.has_key? :name and temp.has_key? :id_parent_folder
      flash_message(:error, t('error.provide_create_parameters'))
      redirect_to root_path
    end
    temp
  end

end

app/views/folders/_contents.erb
<div class="row">
  <div class="col-lg-3 col-md-4 col-sm-6 portfolio-item", style="padding-bottom: 5%">
    <div class="card h-100 text-center">
      <div class="card-body">
        <h4 class="card-title"><%= current_folder.name %></h4>
        <p class="card-text">
          <% unless current_folder.root? %>
              <b> <%= t('created') %> </b><%= current_folder.created_at%>
              <br>
              <b> <%= t('updated') %> </b><%= current_folder.updated_at%>
          <% end %>
        </p>
      </div>

      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <%= link_to "#{t('create')} #{t('folder.folder')} #{t('here')}", new_folder_path(:id_parent_folder => current_folder.root? ?  -1 : current_folder.id ), html_options={class: 'btn btn-primary '} %>
        </li>
        <li class="list-group-item">
          <%= link_to "#{t('upload')} #{t('file')} #{t('here')}", new_document_path(:id_parent_folder => current_folder.root? ? -1 : current_folder.id ), html_options={class: 'btn btn-primary '} %>

      <% unless current_folder.root? %>
          <li class="list-group-item">
            <%= link_to "#{t('editing')} #{t('folder.folder')}", edit_folder_path(current_folder.id), html_options={class: 'btn btn-primary '} %>
          </li>
          <li class="list-group-item">
            <%= link_to "#{t('delete')} #{t('folder.folder')}", folder_path(current_folder.id), html_options={class: 'btn btn-danger ', method: :delete} %>
          </li>
      <% end %>
      </ul>
    </div>
  </div>



<% contents.each_with_index do |object, index| %>
    <% if index != 0 and (index + 1) % 4 == 0 %>
        </div>
        <div class="row">
    <% end %>


    <div class="col-lg-3 col-md-4 col-sm-6 portfolio-item", style="padding-bottom: 5%">
      <div class="card h-100 text-center">
        <% if object.type.zero? %>
            <%= image_tag("file_icon.png", size: "100x100", :alt => "icon folder", class: 'mx-auto d-block') %>
        <% else %>
            <%= image_tag("folder_icon.jpg", size: "100x100", :alt => "icon folder", class: 'mx-auto d-block') %>
        <% end %>
        <div class="card-body">
          <h4 class="card-title">
            <% if object.type.zero? %>
              <%= link_to object.name, document_path(object.id)%>
            <% else %>
              <%= link_to object.name, folder_path(object.id)%>
            <% end %>

          </h4>
          <p class="card-text">
            <b> <%= t('created') %> </b><%= object.created_at%>
            <br>
            <b> <%= t('updated') %>  </b><%= object.updated_at%>
          </p>
        </div>
      </div>
    </div>
<% end %>
</div>

app/views/folders/_form.html.erb
<%= simple_form_for(@folder, url: folder_path(@folder.id), method: method) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <% if @fixed %>
        <% if @folder.id_parent_folder.nil? %>
            <%= f.input :id_parent_folder,
                              as: :select,
                              collection: [] ,
                              :include_blank => '/',
                              :label_method => lambda { |parent| "#{parent.full_path}" } %>
        <% else %>
            <%= f.input :id_parent_folder,
                              as: :select,
                              collection: @collection,
                              :include_blank => false,
                              :label_method => lambda { |parent| "#{parent.full_path}" } %>
        <% end %>
    <% else %>
        <%= f.input :id_parent_folder,
                          :include_blank => '/',
                          collection: @collection,
                          :label_method => lambda { |parent| "#{parent.full_path}" } %>
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, ( f.object.id.nil? ? t('helpers.submit.folder.create')  : t('helpers.submit.folder.edit')) %>
  </div>
<% end %>

app/views/folders/destroy.erb
<div class="container alert alert-danger show">

    <h1 class="text-center"><%= "¡Cuidado! ¡La carpeta que desea eliminar contiene elementos!" %></h1>
</div>
<br>
  <h3 class="text-center"><%= '¿Esta seguro de que desea eliminarla?' %></h3>

<div class="container">

  <br>
  <div class="row">
    <div class="col-sm text-center">
      <%= link_to "#{t('delete')} #{t('folder.folder')}", folder_path(@id, force: 1), html_options={class: 'btn btn-danger', method: :delete} %>
    </div>
    <div class="col-sm  text-center">
      <%= link_to t('back'), folder_path(@id), html_options={class: 'btn btn-primary'} %>
    </div>
  </div>
</div>

app/views/folders/edit.html.erb
<h1> <%= "#{t('editing')} #{t('document.document')}" %> </h1>

<%= render 'form', folder: @folder, method: :patch %>
<br>
<%= link_to t('show'), @folder %> |
<%= link_to t('back'), folders_path %>

app/views/folders/index.html.erb
<h1> <%= t('folder.folders') %> </h1>
<h2> <%= t('path') %> / </h2>


<%= render 'contents', :contents=>@contents, :current_folder=>@current_folder %>

<br>

app/views/folders/new.html.erb
<h1> <%= "#{t('new')} #{t('folder.folder')}" %> </h1>

<%= render 'form', folder: @folder %>
<br>
<%= link_to t('back'), folders_path %>

app/views/folders/show.html.erb
<h2><%= t('path') %>  <%= @folder.full_path %></h2>
<br>


<%= render 'contents', :contents=>@contents, :current_folder=>@folder %>