config/routes.rb
Rails.application.routes.draw do
  get 'login', :to => 'session#login', :as => :new_session
  post 'authorize', :to => 'session#authorize', :as => :authorize
  get 'callback', :to => 'session#callback', :as => :oauth_callback


  delete 'session/logout', :as => :destroy_session

  resources :folders

  resources :files, controller: 'documents', as: 'documents' do
    get 'upgrade', on: :member
  end

  root to: 'session#login'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/session.rb
class Session
  include ActiveModel::Model
  attr_accessor :app_id, :app_secret, :url, :access_token, :callback, :scopes

  def initialize(options=nil)
    super(options)
    @scopes = if @scopes.nil? then
                %w(read write delete)
              else
                @scopes.kind_of?(Array) ? @scopes : @scopes.split(' ')
              end
    @client = OAuth2::Client.new(@app_id, @app_secret, site: @url)
    @callback = URI.join($root_url, Rails.application.routes.url_helpers.oauth_callback_path)
  end

  def authorize
    URI.unescape(@client.auth_code.authorize_url(redirect_uri: @callback.to_s, scope: @scopes.join('+' )))
  end

  def get_access_token(code)
    @access_token = @client.auth_code.get_token(code, redirect_uri: @callback.to_s)
  end

  def to_json_string
    temp = {app_id: @app_id,
            app_secret: @app_secret,
            url: @url,
            callback: @callback.to_s,
            scopes: @scopes
    }
    unless @access_token.nil?
      temp[:access_token] = @access_token.to_hash
    end
    temp.to_json
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def login
    if get_current_session.nil?
      @new_session = Session.new
    else
      @current_session = get_current_session
    end

  end

  def authorize
    if (session_params.keys & %w(app_id app_secret url)).size == 3
      temp = Session.new(session_params)
      if temp.valid?
        session[:current_session] = temp.to_json_string
        @redirect_url = temp.authorize
      else
        render new_session_path, error: t('session.missing_params')
      end
    else
      render root_path, error: t('session.missing_params')
    end
  end

  def logout
    session[:current_session] = nil
    redirect_to root_url, notice: "Logged out!"
  end

  def callback
    temp = Session.new(get_current_session)
    temp.get_access_token(callback_params[:code])
    session[:current_session] = temp.to_json_string
    @current_session = get_current_session
    redirect_to root_path, notice: "Successfully initialized session with #{temp.url}"
  end

  private

  def session_params
    params.require(:session).permit(:app_id, :app_secret,:url)
  end

  def callback_params
    params.permit( :code)
  end

end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/session/_session_form.erb
<%= simple_form_for new_session, url: authorize_path do |f| %>

  <div class="form-inputs">
    <%= f.input :app_id, as: :string, input_html: { class: 'form-control' } %>
    <%= f.input :app_secret, as: :string, input_html: { class: 'form-control' } %>
    <%= f.input :url, as: :string, input_html: { class: 'form-control' } %>
    <%= f.input :scopes, as: :string, input_html: { class: 'form-control' } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/session/_session_view.erb
<pre>
<%= JSON.pretty_generate(current_session) %>
</pre>

app/views/session/authorize.erb
<meta http-equiv="refresh" content="0; url=<%= @redirect_url %>" />

<%= image_tag 'loading.gif' %>

app/views/session/login.html.erb
<h1>Session Login</h1>

<% if @current_session.nil? %>
  <%= render partial: 'session/session_form', locals: {new_session: @new_session} %>
<% else %>
  <%= render partial: 'session/session_view', locals: {current_session: @current_session} %>
<% end %>

app/views/session/logout.html.erb
<h1>Session#logout</h1>
<p>Find me in app/views/session/logout.html.erb</p>