config/routes.rb
Rails.application.routes.draw do
  get 'login', :to => 'session#login', :as => :new_session
  post 'authorize', :to => 'session#authorize', :as => :authorize
  get 'callback', :to => 'session#callback', :as => :oauth_callback


  delete 'session/logout', :as => :destroy_session

  resources :folders

  resources :files, controller: 'documents', as: 'documents' do
    get 'upgrade', on: :member
  end

  root to: 'session#login'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash_message.erb
<div class="container">
  <div class="alert <%= bootstrap_class_for(type) %> alert-dismissible fade show" role="alert">
    <% if type == 'error' && message.is_a?(Array) %>
        <p><%= message[0] %></p>
        <ul>
          <% message[1].each do |p| %>
              <li><%= p.second.first %></li>
          <% end %>
        </ul>
    <% else %>
        <p><%= message %></p>
    <% end %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
</div>

app/views/layouts/_footer.erb
<!-- Footer -->
<footer class="footer py-2 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; DocArk 2017</p>
  </div>
  <!-- /.container -->
</footer>

app/views/layouts/_navbar.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <%= link_to 'DocArk', root_path, class: 'navbar-brand' %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <span class="navbar-text" style="padding-right: 12px">
          <%= link_to 'Home',root_path %>
        </span>
        </li>
        <li class="nav-item active">
          <span class="navbar-text" style="padding-right: 12px">
          <%= link_to 'Log Out', destroy_session_path, method: :delete%>
        </span>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cliente ILI-258 Grupo 5</title>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render 'layouts/navbar'  %>
<br>
<%= render_flash %>
<div class="container pb-2">
  <%= yield %>
  <br>
  <br>
</div>
<br>
<%= render 'layouts/footer' %>

</body>
</html>